name = "BracketedTrees"
uuid = "3f2b6ece-c159-11e9-1602-9b3817a98916"
authors = ["David Ellison <davidehellison@gmail.com>"]
version = "0.1.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Automa = "67c07d97-cdcb-5c2c-af73-a7f9c32a568b"

[compat]
AbstractTrees = "0.2.1"
Automa = "0.8.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
